version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./burndown.sql:/docker-entrypoint-initdb.d/burndown.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=burndown

  app:
    image: phpmyadmin/phpmyadmin:4.8.2
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1

  application:
    build: .
    command: "npm run dev"
    env_file: .env
    ports:
    - "85:8080"
    volumes:
    - ./.:/app
    - ./node_modules:/app/node_modules

  gulp:
    build: .
    image: "app-gulp"
    depends_on:
      - application
    command: "npm run gulp"
    volumes:
      - ./.:/app
      - ./node_modules:/app/node_modules

volumes:
  db_data:
